import {
  Activity,
  Apple,
  BedDouble,
  Brain,
  Building2,
  Clock,
  Coffee,
  Droplet,
  Droplets,
  Ear,
  Flame,
  Footprints,
  Gauge,
  Headphones,
  Heart,
  HeartPulse,
  Moon,
  Mountain,
  Percent,
  PersonStanding,
  Ruler,
  Route,
  Salad,
  Scale,
  Smile,
  Soup,
  Sunrise,
  Thermometer,
  Timer,
  UtensilsCrossed,
  Volume2,
  Weight,
  Wheat,
  Wind,
  Zap,
  type LucideIcon,
} from 'lucide-react'

import type { HealthCategory } from '@/types/apps/health'

export const categoryIcons: Record<HealthCategory, LucideIcon> = {
  activity: Activity,
  heart: HeartPulse,
  sleep: Moon,
  body: Scale,
  vitals: Thermometer,
  mindfulness: Brain,
  hearing: Ear,
  nutrition: Apple,
  mobility: Footprints,
}

export const categoryNames: Record<HealthCategory, string> = {
  activity: '活动',
  heart: '心脏',
  sleep: '睡眠',
  body: '身体测量',
  vitals: '生命体征',
  mindfulness: '正念',
  hearing: '听觉',
  nutrition: '营养',
  mobility: '移动能力',
}

export const metricIcons: Record<string, LucideIcon> = {
  steps: Footprints,
  activeEnergy: Flame,
  exerciseMinutes: Timer,
  standHours: PersonStanding,
  distance: Route,
  flights: Building2,
  heartRate: HeartPulse,
  restingHeartRate: Heart,
  hrv: Activity,
  vo2Max: Wind,
  bloodPressure: Gauge,
  heartRateRecovery: Zap,
  sleepDuration: BedDouble,
  bedtime: Moon,
  wakeTime: Sunrise,
  sleepConsistency: Clock,
  weight: Weight,
  bmi: Percent,
  bodyFat: Gauge,
  height: Ruler,
  bodyTemperature: Thermometer,
  respiratoryRate: Wind,
  bloodOxygen: Droplets,
  wristTemperature: Thermometer,
  mindfulMinutes: Brain,
  stateOfMind: Smile,
  moodRecords: Smile,
  headphoneAudio: Headphones,
  environmentalAudio: Volume2,
  water: Droplet,
  caffeine: Coffee,
  dietaryEnergy: UtensilsCrossed,
  macros: Salad,
  fiber: Wheat,
  sodium: Soup,
  walkingSpeed: Gauge,
  stepLength: Ruler,
  walkingAsymmetry: Footprints,
  stairSpeed: Mountain,
  sixMinuteWalk: Route,
}
