import type { AiAvatarExpression, AvatarVisual } from './types'

export const AI_AVATAR_VISUALS = {
  idle: { label: '待机', body: 'soft', eyes: 'open', brows: 'none', mouth: 'none', effect: 'none', motion: 'breathe' },
  neutral: { label: '平静', body: 'round', eyes: 'open', brows: 'none', mouth: 'small-smile', effect: 'none', motion: 'breathe' },
  happy: { label: '开心', body: 'soft', eyes: 'happy', brows: 'happy', mouth: 'smile', effect: 'sparkles', motion: 'bounce' },
  joyful: { label: '大笑', body: 'wide', eyes: 'happy', brows: 'happy', mouth: 'grin', effect: 'sparkles', motion: 'bounce' },
  excited: { label: '兴奋', body: 'tall', eyes: 'wide', brows: 'raised', mouth: 'open', effect: 'sparkles', motion: 'bounce' },
  playful: { label: '调皮', body: 'soft', eyes: 'wink', brows: 'happy', mouth: 'smile', effect: 'sparkles', motion: 'tilt', tilt: -7 },
  proud: { label: '自信', body: 'wide', eyes: 'focused', brows: 'happy', mouth: 'small-smile', effect: 'none', motion: 'float', tilt: -3 },
  relieved: { label: '放松', body: 'squash', eyes: 'closed', brows: 'happy', mouth: 'smile', effect: 'none', motion: 'breathe' },
  affectionate: { label: '喜爱', body: 'soft', eyes: 'happy', brows: 'happy', mouth: 'smile', effect: 'hearts', motion: 'float' },
  shy: { label: '害羞', body: 'soft', eyes: 'look-down', brows: 'happy', mouth: 'small-smile', effect: 'hearts', motion: 'tilt', tilt: 5 },
  thinking: { label: '思考', body: 'triangle', eyes: 'look-up', brows: 'thinking', mouth: 'flat', effect: 'orbit', motion: 'think', tilt: -5 },
  focused: { label: '专注', body: 'tall', eyes: 'focused', brows: 'thinking', mouth: 'flat', effect: 'none', motion: 'breathe' },
  curious: { label: '好奇', body: 'soft', eyes: 'uneven', brows: 'raised', mouth: 'o', effect: 'question', motion: 'tilt', tilt: 7 },
  confused: { label: '疑惑', body: 'soft', eyes: 'uneven', brows: 'thinking', mouth: 'wave', effect: 'question', motion: 'tilt', tilt: -6 },
  skeptical: { label: '怀疑', body: 'wide', eyes: 'sleepy', brows: 'thinking', mouth: 'flat', effect: 'question', motion: 'tilt', tilt: 4 },
  inspired: { label: '灵感', body: 'tall', eyes: 'wide', brows: 'raised', mouth: 'smile', effect: 'idea', motion: 'bounce' },
  surprised: { label: '惊讶', body: 'round', eyes: 'wide', brows: 'raised', mouth: 'o', effect: 'sparkles', motion: 'bounce' },
  sad: { label: '难过', body: 'squash', eyes: 'sad', brows: 'sad', mouth: 'frown', effect: 'none', motion: 'float' },
  worried: { label: '担忧', body: 'soft', eyes: 'sad', brows: 'sad', mouth: 'wave', effect: 'sweat', motion: 'shake' },
  nervous: { label: '紧张', body: 'tall', eyes: 'wide', brows: 'sad', mouth: 'flat', effect: 'sweat', motion: 'shake' },
  disappointed: { label: '失望', body: 'squash', eyes: 'look-down', brows: 'sad', mouth: 'frown', effect: 'none', motion: 'float' },
  frustrated: { label: '无奈', body: 'wide', eyes: 'closed', brows: 'angry', mouth: 'wave', effect: 'dots', motion: 'shake' },
  angry: { label: '生气', body: 'triangle', eyes: 'angry', brows: 'angry', mouth: 'frown', effect: 'warning', motion: 'shake', tilt: -2 },
  embarrassed: { label: '尴尬', body: 'soft', eyes: 'look-left', brows: 'sad', mouth: 'wave', effect: 'sweat', motion: 'tilt', tilt: 5 },
  tired: { label: '疲惫', body: 'squash', eyes: 'sleepy', brows: 'none', mouth: 'flat', effect: 'dots', motion: 'float' },
  sleepy: { label: '困倦', body: 'squash', eyes: 'closed', brows: 'none', mouth: 'o', effect: 'zzz', motion: 'sleep', tilt: 4 },
  listening: { label: '倾听', body: 'tall', eyes: 'look-right', brows: 'raised', mouth: 'none', effect: 'pulse', motion: 'listen', tilt: 3 },
  speaking: { label: '说话', body: 'soft', eyes: 'open', brows: 'happy', mouth: 'talk', effect: 'pulse', motion: 'speak' },
  processing: { label: '处理中', body: 'triangle', eyes: 'focused', brows: 'thinking', mouth: 'none', effect: 'orbit', motion: 'spin' },
  searching: { label: '搜索中', body: 'soft', eyes: 'look-right', brows: 'thinking', mouth: 'flat', effect: 'search', motion: 'think', tilt: 4 },
  success: { label: '完成', body: 'tall', eyes: 'happy', brows: 'happy', mouth: 'grin', effect: 'success', motion: 'bounce' },
  warning: { label: '提醒', body: 'triangle', eyes: 'wide', brows: 'raised', mouth: 'o', effect: 'warning', motion: 'nod' },
  error: { label: '出错', body: 'squash', eyes: 'dizzy', brows: 'sad', mouth: 'frown', effect: 'error', motion: 'shake' },
  offline: { label: '离线', body: 'round', eyes: 'closed', brows: 'none', mouth: 'flat', effect: 'offline', motion: 'sleep' },
} satisfies Record<AiAvatarExpression, AvatarVisual>
